### ISSUE TITLE
In Chinese translation, certain characters cannot be displayed

### ISSUE THREAD

**Issue by DavidLiang1129** [Tuxemon/Tuxemon#1532]
**Describe the bug**
 
Thanks to @NeonFlames's work, now the Chinese translation can work, but a new problem has arisen, some Chinese characters cannot be displayed, possibly due to the font, I am sorry that I may have chosen a bad font,I'll find a better font

**To Reproduce**
Modify Tuxemon.cfg, change the region to zh_CN so that the game shows the Chinese translation, and you will notice that some Chinese characters are missing

**Expected behavior**
All Chinese characters should be displayed correctly

**Screenshots**
![1.PNG](https://user-images.githubusercontent.com/118408976/210197897-1296143e-4713-46aa-8b8d-d011b567e2ce.PNG)![2.PNG](https://user-images.githubusercontent.com/118408976/210197903-5e7ab2da-dfca-4d4f-9cc1-346f70378f8c.PNG)![3.PNG](https://user-images.githubusercontent.com/118408976/210197908-f65a68b3-4765-48df-bd6e-3989dcdce809.PNG)![4.PNG](https://user-images.githubusercontent.com/118408976/210197914-e830078d-4d7c-483f-8b83-b4b45f0e18a7.PNG)

**Desktop (please complete the following information):**
 - OS: Windows 7 Enterprise edition Chinese version
 - Python Version 3.8

**Smartphone (please complete the following information):**
N/A

**Additional context**

I created a new Openoffice Winter document to test the problem, and you can see that the missing font was replaced with the system default font 
![5.PNG](https://user-images.githubusercontent.com/118408976/210198192-8ccadba5-70db-4d73-850f-a6d8fdd5edb7.PNG)

**Comment by JaskRendix** [comment]
It can help you: https://fonts.google.com/
Just digit the character and you can see if the font has it.

**Comment by DavidLiang1129** [comment]
> It can help you: https://fonts.google.com/
> Just digit the character and you can see if the font has it.

Sorry, no, it can't, because mainland China can't use anything from Google

**Comment by DavidLiang1129** [comment]
> It can help you: https://fonts.google.com/
> Just digit the character and you can see if the font has it.

But I found some new Chinese and Japanese fonts, and I noticed that the font that came with Tuxemon was smaller than the file size of any of the fonts I downloaded, which could mean it wasn't complete.
![6.PNG](https://user-images.githubusercontent.com/118408976/210205210-fea78ff9-562b-4f5f-a01a-be6431da3056.PNG)
![Screenshot_2023-01-02-14-28-46-78_55bef12f624c2b805189a6aa783c400d.jpg](https://user-images.githubusercontent.com/118408976/210205227-a72d824a-5153-4ab1-89c2-e9ce04769296.jpg)
![Screenshot_2023-01-02-14-28-57-50_55bef12f624c2b805189a6aa783c400d.jpg](https://user-images.githubusercontent.com/118408976/210205233-c9bcff16-020c-4650-ab56-4218ed48ea1a.jpg)

**Comment by DavidLiang1129** [comment]
> It can help you: https://fonts.google.com/
> Just digit the character and you can see if the font has it.

Here is the download link of these fonts (download link is provided by Tsinghua Open Source Mirror)
Chinese:
https://mirrors.tuna.tsinghua.edu.cn/adobe-fonts/source-han-serif/SubsetOTF/SourceHanSerifCN.zip
Japanese:
https://mirrors.tuna.tsinghua.edu.cn/adobe-fonts/source-han-serif/SubsetOTF/SourceHanSerifJP.zip

**Comment by JaskRendix** [comment]
Excellent, I checked and the license is OK (SIL OPEN FONT LICENSE).

Which one is the best? Bold, ExtraLight, Heavy, Light, Medium, Regular or SemiBold?

I think the one we have now is Heavy (extra bold)

**Comment by DavidLiang1129** [comment]
> Excellent, I checked and the license is OK (SIL OPEN FONT LICENSE).
> 
> Which one is the best? Bold, ExtraLight, Heavy, Light, Medium, Regular or SemiBold?
> 
> I think the one we have now is Heavy (extra bold)

In my opinion, we should choose the largest file size

**Comment by DavidLiang1129** [comment]
> Excellent, I checked and the license is OK (SIL OPEN FONT LICENSE).
> 
> Which one is the best? Bold, ExtraLight, Heavy, Light, Medium, Regular or SemiBold?
> 
> I think the one we have now is Heavy (extra bold)

I think if the font is not complete, a nice style doesn't mean much. What is your opinion?

**Comment by JaskRendix** [comment]
I agree with you. So the largest file.

**Comment by DavidLiang1129** [comment]
> I agree with you. So the largest file.

Thanks.

**Comment by kerizane** [comment]
Should be fixed now.

**Comment by DavidLiang1129** [comment]
> Should be fixed now.

Thank you for your work on this

**Comment by DavidLiang1129** [comment]
> Should be fixed now.

Sorry, I downloaded the latest development version, but the problem still exists, the font does not seem to have been changed.

**Comment by JaskRendix** [comment]
It works on Linux. Let's wait a couple of PRs, maybe the windows version was too early. Did you try to clean cookies, etc?

![Screenshot from 2023-01-04 11-43-20](https://user-images.githubusercontent.com/64643719/210538456-6309b963-8650-4226-a8d1-245f6672bda0.png)

**Comment by DavidLiang1129** [comment]
> It works on Linux. Let's wait a couple of PRs, maybe the windows version was too early. Did you try to clean cookies, etc?
> 
> ![Screenshot from 2023-01-04 11-43-20](https://user-images.githubusercontent.com/64643719/210538456-6309b963-8650-4226-a8d1-245f6672bda0.png)
> 
Ok, I'll try. Thank you

**Comment by DavidLiang1129** [comment]
> It works on Linux. Let's wait a couple of PRs, maybe the windows version was too early. Did you try to clean cookies, etc?
> 
> ![Screenshot from 2023-01-04 11-43-20](https://user-images.githubusercontent.com/64643719/210538456-6309b963-8650-4226-a8d1-245f6672bda0.png)
> 

I downloaded the latest development version for today, and now there is no problem.
