### ISSUE TITLE
Implement Functional Saving/Loading

### ISSUE THREAD

**Issue by ShadowApex** [Tuxemon/Tuxemon#6]
Right now there is some basic functionality in place for saving, but not for loading. We need to ensure we save all needed variables and write a system to load those variables from a save file.

**Comment by superman2k5** [comment]
I've fixed saving and created loading with #89 :)

**Comment by ShadowApex** [comment]
Saving/loading was broken after the latest state/menu refactor, so this issue still needs to be resolved.

**Comment by bitcraft** [comment]
I'm working on a fix now

**Comment by ShadowApex** [comment]
Resolved in #115
