### ISSUE TITLE
game crashes when you go to route 3

### ISSUE THREAD

**Issue by jinna124** [Tuxemon/Tuxemon#868]
When I go to route 3 from leather town I get the following error:
```
2021-04-18 11:16:49,812 - tuxemon.core.graphics - ERROR - Tile bounds outside bounds of tileset image
Traceback (most recent call last):
  File "d:/coding/MY_coding_stuff/pycharm_coding/games/pygames/rpg/Tuxemon-development/run_tuxemon.py", line 55, in <module>
    main.main(load_slot=args.slot)
  File "d:\coding\MY_coding_stuff\pycharm_coding\games\pygames\rpg\Tuxemon-development\tuxemon\core\main.py", line 106, in main
    client.main()
  File "d:\coding\MY_coding_stuff\pycharm_coding\games\pygames\rpg\Tuxemon-development\tuxemon\core\client.py", line 257, in main
    update(clock_tick)
  File "d:\coding\MY_coding_stuff\pycharm_coding\games\pygames\rpg\Tuxemon-development\tuxemon\core\client.py", line 313, in update
    self.update_states(time_delta)
  File "d:\coding\MY_coding_stuff\pycharm_coding\games\pygames\rpg\Tuxemon-development\tuxemon\core\client.py", line 337, in update_states
    state.update(dt)
  File "d:\coding\MY_coding_stuff\pycharm_coding\games\pygames\rpg\Tuxemon-development\tuxemon\core\states\world\worldstate.py", line 262, in update
    super().update(time_delta)
  File "d:\coding\MY_coding_stuff\pycharm_coding\games\pygames\rpg\Tuxemon-development\tuxemon\core\state.py", line 166, in update
    self.animations.update(time_delta)
  File "C:\Users\codie\AppData\Local\Programs\Python\Python37\lib\site-packages\pygame\sprite.py", line 531, in update
    sprite.update(*args, **kwargs)
  File "d:\coding\MY_coding_stuff\pycharm_coding\games\pygames\rpg\Tuxemon-development\tuxemon\core\animation.py", line 215, in update
    self.finish()
  File "d:\coding\MY_coding_stuff\pycharm_coding\games\pygames\rpg\Tuxemon-development\tuxemon\core\animation.py", line 225, in finish
    self._execute_callbacks("on interval")
  File "d:\coding\MY_coding_stuff\pycharm_coding\games\pygames\rpg\Tuxemon-development\tuxemon\core\animation.py", line 93, in _execute_callbacks
    [cb() for cb in callbacks]
  File "d:\coding\MY_coding_stuff\pycharm_coding\games\pygames\rpg\Tuxemon-development\tuxemon\core\animation.py", line 93, in <listcomp>
    [cb() for cb in callbacks]
  File "d:\coding\MY_coding_stuff\pycharm_coding\games\pygames\rpg\Tuxemon-development\tuxemon\core\states\world\worldstate.py", line 215, in handle_delayed_teleport
    self.change_map(map_name)
  File "d:\coding\MY_coding_stuff\pycharm_coding\games\pygames\rpg\Tuxemon-development\tuxemon\core\states\world\worldstate.py", line 890, in change_map    
    map_data = self.load_map(map_name)
  File "d:\coding\MY_coding_stuff\pycharm_coding\games\pygames\rpg\Tuxemon-development\tuxemon\core\states\world\worldstate.py", line 921, in load_map      
    return TMXMapLoader().load(map_name)
  File "d:\coding\MY_coding_stuff\pycharm_coding\games\pygames\rpg\Tuxemon-development\tuxemon\core\map_loader.py", line 130, in load
    data = pytmx.TiledMap(filename, image_loader=scaled_image_loader, pixelalpha=True)
  File "C:\Users\codie\AppData\Local\Programs\Python\Python37\lib\site-packages\pytmx\pytmx.py", line 368, in __init__
    self.parse_xml(ElementTree.parse(self.filename).getroot())
  File "C:\Users\codie\AppData\Local\Programs\Python\Python37\lib\site-packages\pytmx\pytmx.py", line 436, in parse_xml
    self.reload_images()
  File "C:\Users\codie\AppData\Local\Programs\Python\Python37\lib\site-packages\pytmx\pytmx.py", line 484, in reload_images
    self.images[gid] = loader(rect, flags)
  File "d:\coding\MY_coding_stuff\pycharm_coding\games\pygames\rpg\Tuxemon-development\tuxemon\core\graphics.py", line 284, in load_image
    tile = image.subsurface(rect)
ValueError: subsurface rectangle outside surface area`
```

**Comment by ultidonki** [comment]
Yes: I've confirmed this is happening on the following maps:

- [ ] route3.tmx
- [ ] dryadsgrove.tmx
- [x] spyder_route3.tmx
- [x] spyder_dryadsgrove.tmx

You can replicate with the CLI command:
`teleport 1 1 route3.tmx`

They're all failing on the development branch because the 'Mystery house' tileset has moved - (into the 'core_buildings' tileset now) 

I think the solution is just to remove references to the 'Mystery house' tileset in all the maps, and re-draw the Wayfarer's inn on the route 3 maps using the core_buildings tileset. 

I could probably attempt the fix above, but I don't really understand Tiled yet, so I'm happy if someone else wants to do it instead.

**Comment by ultidonki** [comment]
This is fixed on the Spyder campaign maps now! In pull request #960

**Comment by xirsoi** [comment]
Whoops, just noticed it was still happening on two of the non-spyder maps.
Just gonna bring this to @Qiangong2 's attention so it's not forgotten.

**Comment by Qiangong2** [comment]
I actually had no idea this was happening on route 3. I haven't gotten there yet with story writing because I've been rewriting the beginning

**Comment by ultidonki** [comment]
Yeah, I guess it's not a big deal if the story doesn't actually go there yet and there's nothing to do on the map ;D 

I think it was caused by someone renaming or moving a tileset. If you open the map in tiled, it'll tell you about the problem. 

I'm happy to close it, seeing as there's no story on the map anyway, I'm sure you'll fix it when you get there - or you can leave it open as a reminder to fix if you prefer, either way's fine. :)
